import "dotenv/config"
import { prisma } from "../src/lib/prisma"

const CATEGORIES = [
  {
    name: "Technology & Software Practice",
    slug: "technology",
    description: "Structured digital delivery, product briefs, code reviews, and agile engineering workflows.",
    icon: "Layers",
    sortOrder: 1,
  },
  {
    name: "Business Operations & Strategy",
    slug: "business",
    description: "Operational trackers, status cadence, sprint reviews, and corporate workflow management.",
    icon: "Briefcase",
    sortOrder: 2,
  },
  {
    name: "Design Studio & Visual Systems",
    slug: "design",
    description: "Visual systems, brand identity, user interface reviews, and asset management.",
    icon: "Palette",
    sortOrder: 3,
  },
  {
    name: "Communications & Public Affairs",
    slug: "communications",
    description: "Editorial drafts, stakeholder correspondence, press releases, and structured internal memos.",
    icon: "MessageSquare",
    sortOrder: 4,
  },
  {
    name: "Workplace Practice & Coordination",
    slug: "operations",
    description: "Foundational workplace etiquette, schedule planning, cross-functional collaboration, and deliverables.",
    icon: "Building2",
    sortOrder: 5,
  },
  {
    name: "Artificial Intelligence & ML",
    slug: "ai-machine-learning",
    description: "Applied deep learning, LLM fine-tuning, computer vision, and neural inference pipelines.",
    icon: "Sparkles",
    sortOrder: 6,
  },
  {
    name: "Data Science & Research",
    slug: "research",
    description: "Secondary research, executive summaries, data synthesis, and comparative institutional benchmarking.",
    icon: "BarChart3",
    sortOrder: 7,
  },
]

const PROGRAMS_DATA = [
  // 1. Digital Practice (Course + Internship)
  {
    title: "Digital Practice",
    slug: "digital-practice",
    type: "COURSE" as const,
    categorySlug: "technology",
    status: "PUBLISHED" as const,
    level: "ALL_LEVELS" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "A structured introduction to digital product work, covering research, delivery habits, and documentation.",
    description: "Digital Practice is designed for students who want guided exposure to how digital work is planned, executed, and recorded. The program pairs learning modules with a related internship so experience and documentation stay connected.",
    highlights: ["Product Briefs", "Agile Task Logs", "Dossier Review", "1-on-1 Milestone Review"],
    learningOutcomes: [
      "Describe a typical digital delivery cycle in plain language",
      "Produce structured notes, task logs, and review summaries",
      "Collaborate against a brief with defined checkpoints",
      "Prepare internship artefacts that support certificate issuance",
    ],
    prerequisites: ["Basic computer literacy", "Commitment to weekly checkpoint submissions"],
    tags: ["Technology", "Product Briefs", "Agile", "Digital Work"],
    duration: "8 weeks",
    durationHours: 120,
    price: 2999,
    discountPrice: 1999,
    rating: 4.9,
    ratingCount: 1240,
    isBestseller: true,
    isFeatured: true,
    thumbnail: {
      id: "thumb-digital-practice",
      url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
    banner: {
      id: "banner-digital-practice",
      url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },
  {
    title: "Digital Practice Supervised Internship",
    slug: "digital-practice-internship",
    type: "INTERNSHIP" as const,
    categorySlug: "technology",
    status: "PUBLISHED" as const,
    level: "ALL_LEVELS" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Supervised internship track applying digital delivery techniques against defined client and studio briefs.",
    description: "Work on structured project briefs, maintain weekly execution logs, and build verifiable proof of work with QR credentials.",
    highlights: ["Weekly Mentored Project Briefs", "Documented Proof of Work Dossier", "Official QR-Verifiable Credential"],
    learningOutcomes: ["Full hands-on sprint reviews", "Documented portfolio work", "Professional mentor sign-off"],
    prerequisites: ["Enrolled in undergraduate/postgraduate program"],
    tags: ["Internship", "Supervised", "Technology", "Verified QR"],
    duration: "8 weeks",
    durationHours: 160,
    price: 2999,
    discountPrice: 1999,
    rating: 4.9,
    ratingCount: 1240,
    isBestseller: true,
    isFeatured: true,
    thumbnail: {
      id: "thumb-digital-practice-internship",
      url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },

  // 2. Business Operations (Course + Internship)
  {
    title: "Business Operations",
    slug: "business-operations",
    type: "COURSE" as const,
    categorySlug: "business",
    status: "PUBLISHED" as const,
    level: "ALL_LEVELS" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Practical exposure to coordination, reporting, and operational follow-through in a student internship setting.",
    description: "Business Operations helps students understand how work moves through a team: briefs, trackers, reviews, and written updates.",
    highlights: ["Ops Trackers", "Status Reports", "Execution Rhythm", "Stakeholder Alignment"],
    learningOutcomes: [
      "Maintain a simple operations tracker",
      "Write concise status updates",
      "Support planning and follow-up cycles",
      "Close an internship with complete records",
    ],
    prerequisites: ["Curiosity for organizational workflows", "Strong written communication"],
    tags: ["Business", "Operations", "Project Management", "Reporting"],
    duration: "8 weeks",
    durationHours: 100,
    price: 2499,
    discountPrice: 1499,
    rating: 4.8,
    ratingCount: 980,
    isBestseller: false,
    isFeatured: true,
    thumbnail: {
      id: "thumb-business-operations",
      url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },
  {
    title: "Business Operations Supervised Internship",
    slug: "business-operations-internship",
    type: "INTERNSHIP" as const,
    categorySlug: "business",
    status: "PUBLISHED" as const,
    level: "ALL_LEVELS" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Applied operational briefs, tracker maintenance, and weekly review checkpoints.",
    description: "Hands-on operational project briefs, documentation of work streams, and supervisor checkpoints.",
    highlights: ["Weekly Operational Checkpoints", "Verified Task Dossier", "Official Completion Certificate"],
    learningOutcomes: ["Execute organizational workflows", "Deliver formal review memos", "Receive verified evaluation"],
    prerequisites: ["Enrollment in college program"],
    tags: ["Internship", "Business", "Supervised", "Operations"],
    duration: "8 weeks",
    durationHours: 140,
    price: 1999,
    discountPrice: 999,
    rating: 4.8,
    ratingCount: 980,
    isBestseller: false,
    isFeatured: true,
    thumbnail: {
      id: "thumb-business-operations-internship",
      url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },

  // 3. Design Studio (Course + Internship)
  {
    title: "Design Studio",
    slug: "design-studio",
    type: "COURSE" as const,
    categorySlug: "design",
    status: "PUBLISHED" as const,
    level: "INTERMEDIATE" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Fundamentals of working with design briefs, asset organization, and iterative review cycles.",
    description: "Design Studio focuses on the documentation side of creative work: understanding briefs, preparing assets for review, and incorporating critique.",
    highlights: ["Visual Systems", "Design Critique", "Portfolio Briefs", "Asset Catalogs"],
    learningOutcomes: [
      "Interpret and structure a design brief",
      "Organize design assets for team handoff",
      "Document feedback and design iterations",
      "Assemble a verifiable design internship dossier",
    ],
    prerequisites: ["Familiarity with Figma or Adobe Suite", "Keen visual eye"],
    tags: ["Design", "Figma", "Visual Systems", "UI/UX"],
    duration: "8 weeks",
    durationHours: 110,
    price: 3499,
    discountPrice: 2499,
    rating: 4.9,
    ratingCount: 850,
    isBestseller: true,
    isFeatured: true,
    thumbnail: {
      id: "thumb-design-studio",
      url: "https://images.unsplash.com/photo-1581291518655-9523c932deb2?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },
  {
    title: "Design Studio Supervised Internship",
    slug: "design-studio-internship",
    type: "INTERNSHIP" as const,
    categorySlug: "design",
    status: "PUBLISHED" as const,
    level: "INTERMEDIATE" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Structured creative briefs, peer reviews, and portfolio documentation in a supervised studio setting.",
    description: "Apply design methodology to real brand and interface briefs with continuous mentor critique.",
    highlights: ["Mentored Design Sprints", "Documented Figma/Asset Files", "QR Verified Credential"],
    learningOutcomes: ["Deliver review-ready design files", "Incorporate constructive critique", "Complete verified proof of work"],
    prerequisites: ["Design portfolio sample or coursework"],
    tags: ["Internship", "Design", "UI/UX", "Portfolio"],
    duration: "8 weeks",
    durationHours: 150,
    price: 2499,
    discountPrice: 1499,
    rating: 4.9,
    ratingCount: 850,
    isBestseller: true,
    isFeatured: true,
    thumbnail: {
      id: "thumb-design-studio-internship",
      url: "https://images.unsplash.com/photo-1581291518655-9523c932deb2?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },

  // 4. Communications Practice (Course + Internship)
  {
    title: "Communications Practice",
    slug: "communications-practice",
    type: "COURSE" as const,
    categorySlug: "communications",
    status: "PUBLISHED" as const,
    level: "ALL_LEVELS" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Writing, editing, and publishing written material in a supervised internship context.",
    description: "Communications Practice prepares students for writing-adjacent roles where clarity, accuracy, and deadline discipline matter.",
    highlights: ["Editorial Drafts", "PR Correspondence", "Review Notes", "Style Guides"],
    learningOutcomes: [
      "Write concise, audience-appropriate drafts",
      "Edit for clarity, consistency, and tone",
      "Manage an editorial schedule",
      "Produce a verifiable writing portfolio",
    ],
    prerequisites: ["Good written English proficiency"],
    tags: ["Communications", "PR", "Editorial", "Content"],
    duration: "8 weeks",
    durationHours: 90,
    price: 2499,
    discountPrice: 1499,
    rating: 4.8,
    ratingCount: 710,
    isBestseller: false,
    isFeatured: true,
    thumbnail: {
      id: "thumb-communications-practice",
      url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },
  {
    title: "Communications Practice Supervised Internship",
    slug: "communications-internship",
    type: "INTERNSHIP" as const,
    categorySlug: "communications",
    status: "PUBLISHED" as const,
    level: "ALL_LEVELS" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Drafting, editing, and stakeholder communication under supervision with verified milestones.",
    description: "Work on live editorial briefs, press notes, and internal communication memos with weekly feedback.",
    highlights: ["Live Written Deliverables", "Editorial Mentorship", "Verified Experience Letter"],
    learningOutcomes: ["Publish polished executive summaries", "Maintain editorial calendars", "Receive formal credential"],
    prerequisites: ["College student in any discipline"],
    tags: ["Internship", "Communications", "Writing", "Supervised"],
    duration: "8 weeks",
    durationHours: 130,
    price: 1999,
    discountPrice: 999,
    rating: 4.8,
    ratingCount: 710,
    isBestseller: false,
    isFeatured: true,
    thumbnail: {
      id: "thumb-communications-internship",
      url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },

  // 5. Workplace Practice (Course + Internship)
  {
    title: "Workplace Practice",
    slug: "workplace-practice",
    type: "COURSE" as const,
    categorySlug: "operations",
    status: "PUBLISHED" as const,
    level: "BEGINNER" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "A foundational program focused on workplace readiness, structured communication, and internship habits.",
    description: "Workplace Practice is designed for students entering their first formal internship. It emphasizes basic professional habits: responding to briefs, managing time, keeping accurate records, and participating constructively in reviews.",
    highlights: ["Work Schedule", "Attendance Logs", "Supervisor Checkpoints", "Professional Etiquette"],
    learningOutcomes: [
      "Follow professional email and messaging norms",
      "Manage daily priorities against a schedule",
      "Document attendance, hours, and task completion",
      "Prepare for formal internship close-out",
    ],
    prerequisites: ["None - ideal for first-time interns"],
    tags: ["Workplace", "Foundational", "Readiness", "Professionalism"],
    duration: "8 weeks",
    durationHours: 80,
    price: 1999,
    discountPrice: 999,
    rating: 4.7,
    ratingCount: 1420,
    isBestseller: true,
    isFeatured: true,
    thumbnail: {
      id: "thumb-workplace-practice",
      url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },
  {
    title: "Workplace Practice Supervised Internship",
    slug: "workplace-practice-internship",
    type: "INTERNSHIP" as const,
    categorySlug: "operations",
    status: "PUBLISHED" as const,
    level: "BEGINNER" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Structured workplace tasks, schedule planning, and supervisory checkpoints.",
    description: "Beginner-friendly internship track building foundational professional proof of work.",
    highlights: ["First-Time Intern Mentoring", "Structured Checkpoint Logs", "Verifiable Credential"],
    learningOutcomes: ["Build verifiable professional record", "Master workplace communication", "Complete certified internship"],
    prerequisites: ["First or second year undergraduate students welcome"],
    tags: ["Internship", "Workplace", "Entry Level", "Verified"],
    duration: "8 weeks",
    durationHours: 120,
    price: 1499,
    discountPrice: 799,
    rating: 4.7,
    ratingCount: 1420,
    isBestseller: true,
    isFeatured: true,
    thumbnail: {
      id: "thumb-workplace-practice-internship",
      url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },

  // 6. Research Support (Course + Internship)
  {
    title: "Research Support",
    slug: "research-support",
    type: "COURSE" as const,
    categorySlug: "research",
    status: "PUBLISHED" as const,
    level: "INTERMEDIATE" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Techniques for secondary research, data compilation, source logging, and summary preparation.",
    description: "Research Support trains students in disciplined research habits: identifying credible sources, recording findings systematically, synthesizing data into summaries, and citing references correctly.",
    highlights: ["Source Logs", "Executive Summaries", "Synthesis Notes", "Citation Verification"],
    learningOutcomes: [
      "Conduct systematic secondary research on a defined topic",
      "Maintain a comprehensive, structured source log",
      "Write concise executive summaries and comparison tables",
      "Verify citation accuracy and evidence consistency",
    ],
    prerequisites: ["Strong analytical thinking and reading comprehension"],
    tags: ["Research", "Analysis", "Data", "Synthesis"],
    duration: "8 weeks",
    durationHours: 100,
    price: 2999,
    discountPrice: 1999,
    rating: 4.8,
    ratingCount: 630,
    isBestseller: false,
    isFeatured: true,
    thumbnail: {
      id: "thumb-research-support",
      url: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },
  {
    title: "Research & Analytics Supervised Internship",
    slug: "research-support-internship",
    type: "INTERNSHIP" as const,
    categorySlug: "research",
    status: "PUBLISHED" as const,
    level: "INTERMEDIATE" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "Applied secondary research briefs, data synthesis, and literature review under mentor supervision.",
    description: "Conduct in-depth secondary market analysis, structured data synthesis, and comparative benchmarking.",
    highlights: ["Analytical Research Briefs", "Published Whitepaper Dossier", "QR Verified Experience Certificate"],
    learningOutcomes: ["Deliver structured industry analysis", "Master executive writing", "Gain verified research credentials"],
    prerequisites: ["Undergraduate or postgraduate student"],
    tags: ["Internship", "Research", "Analytics", "Supervised"],
    duration: "8 weeks",
    durationHours: 140,
    price: 2199,
    discountPrice: 1299,
    rating: 4.8,
    ratingCount: 630,
    isBestseller: false,
    isFeatured: true,
    thumbnail: {
      id: "thumb-research-support-internship",
      url: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },

  // 7. Advanced Engineering Masterclasses
  {
    title: "Masterclass in Full Stack Web Engineering",
    slug: "masterclass-full-stack-web-engineering",
    type: "COURSE" as const,
    categorySlug: "technology",
    status: "PUBLISHED" as const,
    level: "INTERMEDIATE" as const,
    deliveryMode: "HYBRID" as const,
    shortDescription: "End-to-end full stack architecture from relational database design to React 19 SSR micro-frontends.",
    description: "Master modern full-stack web engineering with production-grade TypeScript, PostgreSQL, Prisma, caching layers, and high-performance server architectures.",
    highlights: ["50+ Production Deployments", "PostgreSQL & Redis Caching", "1-on-1 Code Reviews", "System Design"],
    learningOutcomes: [
      "Architect multi-tenant database models with Prisma & PostgreSQL",
      "Build high-performance React & TanStack Start applications",
      "Implement JWT authentication and role-based access control",
      "Deploy production applications on modern cloud infrastructure",
    ],
    prerequisites: ["Basic JavaScript/TypeScript knowledge"],
    tags: ["Full Stack", "React", "Node.js", "PostgreSQL", "TypeScript"],
    duration: "12 weeks",
    durationHours: 140,
    price: 18999,
    discountPrice: 14999,
    rating: 4.95,
    ratingCount: 340,
    isBestseller: true,
    isFeatured: true,
    thumbnail: {
      id: "thumb-fullstack-masterclass",
      url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },
  {
    title: "Production Deep Learning & LLM Systems",
    slug: "production-deep-learning-llm-systems",
    type: "COURSE" as const,
    categorySlug: "ai-machine-learning",
    status: "PUBLISHED" as const,
    level: "ADVANCED" as const,
    deliveryMode: "ONLINE" as const,
    shortDescription: "Train, quantize, and deploy foundation models and RAG pipelines for enterprise scale.",
    description: "Build cutting-edge applied AI systems from fine-tuning open-source models to orchestrating retrieval-augmented generation and vector databases.",
    highlights: ["PyTorch & HuggingFace", "Vector Database Indexing", "vLLM Inference Server", "RAG Systems"],
    learningOutcomes: [
      "Fine-tune LLMs with LoRA and PEFT techniques",
      "Design low-latency RAG architectures with hybrid search",
      "Deploy scalable inference endpoints on GPU infrastructure",
      "Evaluate model hallucinations and safety guardrails",
    ],
    prerequisites: ["Python proficiency & basic linear algebra"],
    tags: ["AI", "LLM", "Deep Learning", "PyTorch", "RAG"],
    duration: "12 weeks",
    durationHours: 120,
    price: 24999,
    discountPrice: 19999,
    rating: 4.98,
    ratingCount: 180,
    isBestseller: true,
    isFeatured: true,
    thumbnail: {
      id: "thumb-deep-learning",
      url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1600&q=80",
      format: "jpg",
      provider: "LOCAL",
    },
  },
]

async function seedPrograms() {
  console.log("🌱 Starting Comprehensive Program Categories & Programs Seed...")

  // 1. Seed Categories
  const categoryMap = new Map<string, number>()

  for (const cat of CATEGORIES) {
    const record = await prisma.programCategory.upsert({
      where: { slug: cat.slug },
      update: {
        name: cat.name,
        description: cat.description,
        icon: cat.icon,
        sortOrder: cat.sortOrder,
        isActive: true,
      },
      create: {
        name: cat.name,
        slug: cat.slug,
        description: cat.description,
        icon: cat.icon,
        sortOrder: cat.sortOrder,
        isActive: true,
      },
    })
    categoryMap.set(cat.slug, record.id)
    console.log(`  📁 Category: ${record.name} (#${record.id})`)
  }

  // 2. Seed Programs & Internships
  for (const prog of PROGRAMS_DATA) {
    const categoryId = categoryMap.get(prog.categorySlug)
    if (!categoryId) continue

    const payload = {
      title: prog.title,
      type: prog.type,
      categoryId,
      status: prog.status,
      level: prog.level,
      deliveryMode: prog.deliveryMode,
      shortDescription: prog.shortDescription,
      description: prog.description,
      highlights: prog.highlights as any,
      learningOutcomes: prog.learningOutcomes as any,
      prerequisites: prog.prerequisites as any,
      tags: prog.tags as any,
      duration: prog.duration,
      durationHours: prog.durationHours,
      price: prog.price,
      discountPrice: prog.discountPrice,
      rating: prog.rating,
      ratingCount: prog.ratingCount,
      isBestseller: prog.isBestseller,
      isFeatured: prog.isFeatured,
      isActive: true,
      certificateOffered: true,
      thumbnail: prog.thumbnail as any,
      banner: (prog as any).banner || (prog.thumbnail as any),
    }

    await prisma.program.upsert({
      where: { slug: prog.slug },
      update: payload,
      create: {
        ...payload,
        slug: prog.slug,
      },
    })

    console.log(`  🚀 Seeded Program: [${prog.type}] ${prog.title} (/${prog.slug})`)
  }

  console.log("--------------------------------------------------")
  console.log("🎉 All Program Categories and Programs successfully seeded into PostgreSQL!")
}

seedPrograms()
  .catch((e) => {
    console.error("❌ Seed error:", e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
