/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCertificatesRouteImport } from './routes/admin/certificates'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminInternshipsRouteImport } from './routes/admin/internships'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as InternshipsIndexRouteImport } from './routes/internships/index'
import { Route as InternshipsSlugRouteImport } from './routes/internships/$slug'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ProgramsSlugRouteImport } from './routes/programs/$slug'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentCertificatesRouteImport } from './routes/student/certificates'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentProgramsRouteImport } from './routes/student/programs'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as VerifyCertificateIdRouteImport } from './routes/verify/$certificateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInternshipsRoute = AdminInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InternshipsIndexRoute = InternshipsIndexRouteImport.update({
  id: '/internships/',
  path: '/internships/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsSlugRoute = InternshipsSlugRouteImport.update({
  id: '/internships/$slug',
  path: '/internships/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProgramsRoute = StudentProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => StudentRouteRoute,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateIdRoute = VerifyCertificateIdRouteImport.update({
  id: '/verify/$certificateId',
  path: '/verify/$certificateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/internships': typeof AdminInternshipsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/internships/$slug': typeof InternshipsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/programs': typeof StudentProgramsRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/admin/': typeof AdminIndexRoute
  '/internships/': typeof InternshipsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/internships': typeof AdminInternshipsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/internships/$slug': typeof InternshipsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/programs': typeof StudentProgramsRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/admin': typeof AdminIndexRoute
  '/internships': typeof InternshipsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/student': typeof StudentIndexRoute
  '/verify': typeof VerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/internships': typeof AdminInternshipsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/internships/$slug': typeof InternshipsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/programs': typeof StudentProgramsRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/admin/': typeof AdminIndexRoute
  '/internships/': typeof InternshipsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/services'
    | '/terms-and-conditions'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/internships'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/internships/$slug'
    | '/programs/$slug'
    | '/student/certificates'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/programs'
    | '/verify/$certificateId'
    | '/admin/'
    | '/internships/'
    | '/programs/'
    | '/student/'
    | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/services'
    | '/terms-and-conditions'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/internships'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/internships/$slug'
    | '/programs/$slug'
    | '/student/certificates'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/programs'
    | '/verify/$certificateId'
    | '/admin'
    | '/internships'
    | '/programs'
    | '/student'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/services'
    | '/terms-and-conditions'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/internships'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/internships/$slug'
    | '/programs/$slug'
    | '/student/certificates'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/programs'
    | '/verify/$certificateId'
    | '/admin/'
    | '/internships/'
    | '/programs/'
    | '/student/'
    | '/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  InternshipsSlugRoute: typeof InternshipsSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  VerifyCertificateIdRoute: typeof VerifyCertificateIdRoute
  InternshipsIndexRoute: typeof InternshipsIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/internships': {
      id: '/admin/internships'
      path: '/internships'
      fullPath: '/admin/internships'
      preLoaderRoute: typeof AdminInternshipsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/internships/': {
      id: '/internships/'
      path: '/internships'
      fullPath: '/internships/'
      preLoaderRoute: typeof InternshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships/$slug': {
      id: '/internships/$slug'
      path: '/internships/$slug'
      fullPath: '/internships/$slug'
      preLoaderRoute: typeof InternshipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/programs': {
      id: '/student/programs'
      path: '/programs'
      fullPath: '/student/programs'
      preLoaderRoute: typeof StudentProgramsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateId': {
      id: '/verify/$certificateId'
      path: '/verify/$certificateId'
      fullPath: '/verify/$certificateId'
      preLoaderRoute: typeof VerifyCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminInternshipsRoute: typeof AdminInternshipsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminInternshipsRoute: AdminInternshipsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentProgramsRoute: typeof StudentProgramsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentProgramsRoute: StudentProgramsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  InternshipsSlugRoute: InternshipsSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  VerifyCertificateIdRoute: VerifyCertificateIdRoute,
  InternshipsIndexRoute: InternshipsIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
